### ISSUE TITLE
Release 1.8.2403.1

### ISSUE THREAD

**Issue by damyanp** [microsoft/DirectXShaderCompiler#6420]
This is a bug fix release, therefore changes go into the release branch, which is already in Ask Mode[^1].

```[tasklist]
### Tasks
- [x] Update README.md
- [x] Create draft of Release post on GitHub
- [x] Tag final release and post binaries.
- [x] Create dxc vpack for runtime-relevant metadata
```

```[tasklist]
### Quality Sign-off
- [x] Microsoft Testing Sign-off (@pow2clk)
- [x] Google Testing Sign-off (@sudonatalie)
```
[^1]: [Ask Mode](https://devblogs.microsoft.com/oldnewthing/20140722-00/?p=433) is a Microsoft-ism to denote when changes require approval before accepting merges. For DXC this will require approval from @microsoft/hlsl-release

**Comment by sudonatalie** [comment]
Confirming the `release-1.8.2403` branch still passes Google testing

**Comment by tex3d** [comment]
[Release is live](https://github.com/microsoft/DirectXShaderCompiler/releases/tag/v1.8.2403.1).
