### ISSUE TITLE
Add assertions enabled build of DXC trunk to Compiler Explorer

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/DirectXShaderCompiler#6550]
During triage it is super helpful to be able to know if input that causes a crash also hits asserts. For this purpose it would be extremely useful to have an asserts-enabled build of DXC on Compiler Explorer. There is an asserts-enabled build of Clang trunk on CE, so this has existing analog.

```[tasklist]
### Tasks
- [ ] Add DXC asserts enabled build to the build-dxc script (https://github.com/compiler-explorer/misc-builder)
- [ ] Add DXC asserts enabled build to hlsl build configurations (https://github.com/compiler-explorer/infra)
- [ ] Add DXC asserts enabled build to CE (https://github.com/compiler-explorer/compiler-explorer)
```

**Comment by devshgraphicsprogramming** [comment]
Would be useful because I've recently pulled the latest master and suddenly this shader produces runtime access violation reading address 0x0000000000000008 but only with a debug build of DXC

https://godbolt.org/z/cPcP17Yze

**Comment by devshgraphicsprogramming** [comment]
I have my Godbolt own instance and I have a 8 hourly Debug build of DXC

[Here's an example of very badly mismatched SPIR-V](https://godbolt.dxc.devsh.eu/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1AJaC2qSX1kBPAMqN0AYVS0AriwYgATKQcAZPAZMADl3ACNMYgkADmjSAAdUBUJbBmc3D28EpJSBAKDQlgiorliLTCsbASECJmICdPdPH0tMa1SauoJ8kPDImLiFWvrGzJbh7sDeov7S6IBKC1RXYmR2DmY2BXimNYBqbbxiADcAUg0AQVOAdgAhc4uCTBZ4gyfTgGZHAgBPeMZWJg9gBZUh7X7/TZAgAqYIhALYexqJCYwEwjgMCgUn2wD1OAFZ7oTjgBrEAgTCqAgAfUCQ2IrnaAggAHoAFTbY7kgDy8QuyDWWMcCCYgTZLIAbPj5gSACJyh6k8lCeJHY68pgAR1cmGhf0wn0c7L2vL1/2UqECT2I4r2Hx8yOIqPRmIUpGBOL2u0FCmFooYEAJRNuSopVOpxEwVEijDWCvxsr2oZVao12t1%2BsNxtN%2BotVsitvtpEdzoxTCxpGhnrC5cwYKDQdDlJptEIkTE8cTrit9upBD2gSwqg0Mo%2B90uDyeLzeBq%2ByFde1he3n5YUezkOLxhMbZLDNLpBAZTID7M5PPit0IoiG4q4XkkMoTCsu0L2YSv5YIEDko/HV0uU6vEw7xfPCUKLp6LIsgOgiYGixBrqg/xOk8ewCHsXhrmg07PIw/YKKgByAmh8R7PwxAHHgwBBOgXoMLRrgMMk1GYOgW7Bk24YHkeVQnhy8RciAvKPKgLB4MgACSFzoOg4peB8D6dg8r7AaJ4lSTJgbbsSu7NhGUYxgwcZPgmi57PEh5gt2gi9v2bAsCQPwiEhdZ7NZBC2Xs9mOUIzyGDYyBumZxxiDqv54tc8oTpcULbLsQJhOgTARX%2BsU7PseDTilk7PEBIHfPq4FLmBxHKFZPZeH2XqttRbCCJuE7aSGunhqIOzvq2vysmyygID8ySiLQJZorcrhUNGxDSegkZYpga62viCnXHsj7yk%2BjUcS1%2B5MYejK8RAezsryfioEwsmSlwK1KS%2Bey0Kd6AQMo5mWrBZB7A2OnknpnXtrQnZuRVVXUtSYhUTRnyyuyFw1TR4oaMOGiI0jPjvU1nEtm2Tp/SZXaA/2wOg7VeEQ4TDB1QQ4XRY8uUzoaJWIsVhWleVNmVf2pPkw1Vxo1t1JtUwHWED83W9f14liMNmCjeNkRTTNSjzdBi2SMtq3Ptzm1fVxO08akB1HfEjqYOKEpeFdOOKpatFDCQmCPc9%2BZvR9zVazSkYTbGBo42ZqBhNo9Y8671I/Vj/3uZ5BMw6xENQ1H53w0jico876PB5jHbe%2BHbN7JHYOcx8soc3hlP/hcUGLtysrciAXpEGJgVkSQez4DLkaCOC%2BrYgBNPAbOBWQsRjMD4iyiQdB%2BbwYhyG92hDAYVhomvLh7cEURiJIY3FHMTRdEMUxYPRxtO5B9xe166eAnniJ9caed8mKRbN2qTfU32xZb1Z1V3nEE5aD/CzHls7fycn5QQ4kgqvhCm4TAJcbhRVLg8cu0JK7Vy8kwH4EQ0EkiBAwEgLAxC7z2DNQ84l8KYB2ChIE%2BAhiBGsB3f4a4DyYDOmhKg4Ie5PC7tTacvc6ZMwZmCN8qAXA52IcQUhEMqBiCUFzeke0c7Unfp8P8OUeH5XpjCABnki6CDBGEYRtBRFzRIdYWRu06HAxrEofSVBsqXCQSgkAiDoJ7FcUMYC4kQazXqBAHRBBNwF1JqgKgEBoTzBLq41xrhkhGAUZyRRh4qoQyTLuFMJw0w6jNH3B4kTcmHTZCaeIWS8yvT2IWHwOS8muONKLAaEsiBOhGmNCaZToKhgCNaDsXxQwTyxnzAQ7j6pfHcqQZWABOT0OJSCVKqVWS4uSAkqPmZEhxVca5CFEkCXkexZRtBRKhdCBAEBAhCuIgW9A9gAHdli0Fopghg4kgSrwks3AQYAOD9m0NEshQJTgSg0KcLw%2BJDgnAkoIcR%2B9kBZOpMEP5ALlnVOggAMQkgADWBNgGutw2iuFrKwvYCACAEHiAoEAUFgCEAQK4MIAA6bCLJ67ECSMEggLJZRHDaAQVFQgRRYGIM4F4dBIgsjwFiHUChJT4kkFwPE8k8BsPhRcXJ0TAjAAOAJBJxAkkFziRq9%2BfZlEzPVccTVVUlFjiNcDeJ%2Br8bUjRDSa1h4IAygRe9O4RrcmRgICsOe5q/wLMirKj4FQZGupVbEx1Wr%2BzJPchKSQBqLWusjWaw8hrXUp15vzQWXV2S1PFkNBpzppYTTlnNBWrS9jK1VtdJVkSrV6sSba%2B11JI3OqNTcf1VSiGYG9cQOeILBLvgINefxXx60mptTiCA78ImRLgUGhw8q8SutWaggA6jc2irZsHgkItE35/zk3%2BP%2BWhCiwkBRlr9IEbtChXC0H7EwlhwT3r/NjfG49iqFmBz3HzJg7U6BCxFn1OpBaURNNbqW2aitK1LXNmteBuTjhWwUYEQgEA0A7WNaa/GM723utdbk9%2B70dWarTbW1x86qZfs1j%2BrNAGc09WA/myWxbZYyXlnNCtVa4Pq1ycDc1jhYT6XpBIj42AvTseCW29N%2BHyN5P46mr4QmxGifE16qBZGu3doIFAmlZ1prEcTAO8kQ6R2GjfQm7A07DyzqqV6n12mNOJrk5R0u1Hj60b/QLejwtc1McGix5pbHppls4wtWDat1pydfHdM60mXOycOsitFGKsU4rxc%2BwlxLSXkspdSulokGXiSZQRKgrL2WRmsNy3lkQBWqnoMQEVYq5qSulUG%2BVexP1dvs32gc05ySxbYkpiwDao2kD8VO3DznAXBtMAaAjkSetz0yq8Ab91DRCZbaNvs42Yb5ys8DZtrbwlkZm4u2xMn4Htu/XpOjnVfOMbFgFwt4GS3sdC9B7jkWEORKQ3ga2DS7YYaGMFMQLqEv%2BvLii9FmK9jYuQLipQ%2BKsskrJSyClRz8v0sZcysrbKOVVZ5WdWri8hWNdFbelrUo2sTjlQqj1kSVu0HJDbSMG2RsTsbbtvOxMxPWeILA%2BSIb5tydyUzlngP2fjuw9zomQyDt2p7VtznxBnVgigYL4N9El2XYivKabVNAK01AvwzRANWZVT8eyEmMMpNhPFHogxRiROmILlIubZieIKPdnsGuljaw2PZ340gwmTGjtxBORLkTw1qqsZgbViZ/fWPdkHvbeEQ8qdd7iZzyqYlqqOaKhP3uoyp557o0P4is%2BncDQbsu0FkFrPVW0PAoMABeHiBmb0ojhN83Z73XvhGuI5wECVMGOECZ%2B4DVF5T7p/dmafdFCJERX1TDw5EWMD8MvGsuybp5X1n33Ci4%2Bb8cHPnf5MM/GMr%2BHuxcmY9vgD9Gkj1Jj8p63xbgg5%2B9%2BZ5vzn6PefwQEBC8n9E8T8z9g999f8lkXMbtWovNs0Hs81nswMpYgtJp3soMuMIsa1lU8Za41JkBX5gd%2Bw58kxQoYE8NO07Me0HNxcQBJ9JIppzM8Yp1j8CByRDsldjtSAL5BJnJ/hdljhHlbweD%2BJBJgRngfJQEAoFBgRywSRggBBjYWQNBSAoEwpNM51A1I99doDp9jd%2B4EQzcl9DFIDPd5EFNiBb9c9VVADgDDMFEBNlMr9V8/8okrQ41Ld2NTt01YCaQ7tAM/Mnt6kUDWN0CQtMDwsVYeMotcl3EAo7CFAqpkBIxe50MBkSCPD30c59MBdKCGdXEC8kj%2Bx1MukqC8lSjaA9N2MHCQZvC3CKiaDetKjNCKNtC3NIkjdeF39AFLcF8b9fCaNbt4CfMgNgjQNGlUCIMMDy0ojq1H45NgY39BNSBpAzCxNm4YwQlwcA1yjclV0a5VxIgvxcjAUJQLMTj%2BiABaLgUcfXWUEcHw0Xf/WwyoovJYkvYbNYn/RZAoxzMQKqFohoz1HtXTYGVDL8YzEAUzT8PhYeIEN49gkAI9UgC4qdXIk7YExbJoueIE8o1zedabdo5dC4C4iTCI7EWvdffsZQIQMFeIVwfxSPJZMZKgWLAgSQZcFwJuGuRwbkPwbkAAJWr10JJK6PUVNz2AAGlMAfh%2BQfQSBzC6E0BGIbBYkO0jU/taIIT0jMMyTciy15g3U9jIlsEfhNUHCZS5SL0sQSBfEZjfx3pddXUtSyJnVjS/jEomAOCwDt9pB3cZENiCAXgHCzTNUaVxSqEtjDRJAp1bM8lgz4gaVWc7ZbjWi3UrtXUrT5Sy0m4wy/U9cniM0g4AiGMkCQjJiwjINZilZsCFigwGB3AjlUj0AFAIAgUJRSAuAuy1ZLhXT8FAh4sNTXUVSwEjBDQvSfSBM59JkNjRzrR0z5zIgaUdSDSsR4ylziAaVtiRSOBFhmcOB8ReBPAOAtBSBUBOAAAJPwIQPwA4ZYVYX5eSHgUgdg08vcxYMkD4D4Glb8v8/8gCzsg8yQY8zQXgC8jgXgUlVQt8rQRYOAWAJAbCerSIcgSgZCsnEAdAVQZAakLAMIVwYAakVwElQ8ZhFgPgOga0UlCAMIMC0gd8ZgH%2BTgF8xiuoH4bkP2TlFi3gbCcmbkBgWgH4ei/CwixwMQUwHi0gLAfBIwcQd86SgnGwcfUlBSykHFJ4KS/MA8s81sMIJ0H%2BZwLAeikhFgHixYNk1EBQAANTwEwEuV5EYCkv4EEBEDEHYCkBkEEEUBUHUAUt0G7IMCMBABMDMH0DwDCFJUgEWCQl4lUquIHT2CuIAC14gKIriAQwh6AbiJQh0rjB8kqqBSQrj90ErBo6griDAfhlh%2Bwri11cErjkBAV7gvBbguAuAMqqRGBkhO86qGqmrWrmquBW9Oqnh95er6rUBGrmqhrJBRrurUg1w%2BqprqJXAEragAori2TToCAriITCrOR8q6h7UMqGAzgC5jg70SRDAuBfykrLzrKMINAvBVAkrxMBy54trDrRLgAIYCIVh9gvqBIrifqIYiARErjXxApqQJRqRrhwLx9iBxEsAoq1dWhjx7B6JRhPBuz/AphChig9BEhkheJsaiacheIegCbZhyhKgOgJgybuz0beJOh6gqa%2BgSgLAGaXAmg9B3E2b8aOaJBFh/rHzhb9BOAjzSATyzyIKdlUVHA9gIBdkCLgAjSIBcBCAm4ZtbjeBYKPzSAyRJBJAaVJAvAJQxl/kPgxlogJQPhTZpBgLQKFKIKoKQAYKwL4KYBEAQAaqGTP8KB0jBUGtghAQQBZQFbfB8AGl/s9AXLhBBoPL/TZAfK1B6KArSBLknR4hzKJbDznbZbOBuRGT/b8UI7FblbMBVb1a6syd3pnz5g9bPbPzvAvAaV5IxlrgNBTYJRogNAPgNAza86QLpb6LXaLB3bXzm686vAC7wLOAm73zwk1DIgerPBJAgA%3D%3D)

(sorry short links don't work yet)

How do I make the asserts print a stack or something instead of just
```
Internal compiler error: LLVM Assert
Compiler returned: 3758096385
```
