### ISSUE TITLE
Release 1.8.2407

### ISSUE THREAD

**Issue by damyanp** [microsoft/DirectXShaderCompiler#6752]
# Schedule

- [x] 07/15/2024 - Release branch forks from `main`
    - At this point, changes must be cherry-picked into the release branch in
      order for them to be included in the release.
- [x] 07/18/2024 - Release Candidate 1 (begin Ask Mode[^1] for release branch).
    - At this point, changes must be approved by @microsoft/hlsl-release
- [x] 07/25/2024 - Final Release Candidate
- [x] 07/30/2024 - Target Release Date

# Tasks

## Before Fork

This part of the release process is to 'prime the pump' - that is to make sure
that all the various parts of the engineering system are set into place so that
we are confident we can generate builds for the new branch

- [x] Update version number
- [x] Create the release branch from `main`
    - The release branch is kept into sync with main via regular fast-forward
      merges.
- [x] Internal branches and build pipelines configured
    - Verify that the engineering system can build:
    - [x] Zip files for github release
    - [x] NuGet package
    - [x] VPack
- [x] Final merge of `main` into the release branch

## After Fork

- [x] Update README.md
- [x] Create draft of Release post on GitHub

## Quality Sign Off

- [x] Microsoft Testing Sign-off (@pow2clk)
- [x] Google Testing Sign-off (@s-perron / @Keenuts)

## Release

- [x] Tag final release and post binaries

[^1]: [Ask Mode](https://devblogs.microsoft.com/oldnewthing/20140722-00/?p=433)
    is a Microsoft-ism to denote when changes require approval before accepting
    merges. For DXC this will require approval from @microsoft/hlsl-release

**Comment by s-perron** [comment]
I just tested the release branch, and it passes all of our tests.
