### ISSUE TITLE
DXIL Validator Hash

### ISSUE THREAD

**Issue by python3kgae** [microsoft/DirectXShaderCompiler#6769]
This issue serves as a progress tracker for [DXIL Validator Hash](
https://github.com/microsoft/hlsl-specs/blob/main/proposals/infra/INF-0004-validator-hashing.md)

# Tasks

- [ ] Build the DXIL validator library both as a dynamic and static library to allow full flexibility.
- [ ] Open source the implementation of dxil.dll.
- [ ] Support bypassing Hash Verification.

**Comment by damyanp** [comment]
Setting this to backlog - we're likely to do all the subtasks here, but not necessarily for the same release.
